### ISSUE TITLE
Изменение message в приходящем ответе с API

### ISSUE THREAD

**Issue by PeIIIaJIkuH** [innovember/real-time-forum#6]
внутренняя ошибка сервера - Internal server error
некорректный запрос - Bad request
еmail уже существует - Email already exists
имя пользователя уже существует - Username already exists

Тут только те ошибки, которые потенциально могут показаться юзеру. Те, что типа 404 или 403 пока вроде не нужны.

new user has been created - You have registered successfully

Это тоже будет показываться пользователю.

**Comment by innovember** [comment]
Fixed
